apiVersion: groundupscale.dev/v1alpha1
kind: DeploymentIntent
metadata:
  name: mac-cpu
  version: 0.1.0
spec:
  bindings:
    - scope: workload/transformer-prefill/request/model-prefill
      placement: local-m4/cpu
      strategies: []
